Repository hngprojects/hng_boilerplate_nextjs, pull requests merged in 2024-07, with the labels that each got.

#333 feat/HNG 51 create Integration Card
  src/components/common/IntegrationCard/IntegrationCard.tsx
  src/components/common/IntegrationCard/Integrationcard.test.tsx
Labels: changes requested

#371 Feat/HNG-177: Implement Custom Textarea with Validation and Character Count
  html/assets/index-TpLatVz2.js
  html/assets/index-fUmMsp0O.css
  html/bg.png
  html/favicon.svg
  html/html.meta.json.gz
  html/index.html
  src/app/guides/page.tsx
  src/components/common/CharacterLimitTextarea/CharacterLimitTextarea.tsx
  src/components/common/CharacterLimitTextarea/index.tsx
  src/components/common/CharacterLimitTextarea/useCharacterLimit.tsx
  src/test/CharacterLimitTextarea.test.tsx
Labels: changes requested

#421 Feat/62 password visibility toggle
  src/components/common/PasswordInput/PasswordInputDemo.tsx
  src/components/common/PasswordInput/index.tsx
  src/test/PasswordInput.test.tsx
Labels: changes requested

#343 feat: create reusable datacard component.
  src/components/common/DataCard/DataCard.test.tsx
  src/components/common/DataCard/DataCard.tsx
Labels: changes requested

#301 feat(HNG-68): create a reusable empty list component for career page
  src/components/common/Empty List/EmptyList.test.tsx
  src/components/common/Empty List/EmptyList.tsx
Labels: changes requested

#336 Feat/206 product details component
  public/images/productdetails/default-image.jpg
  public/images/productdetails/product_image.jpg
  public/images/productdetails/test-image.jpg
  src/components/common/ProductDetailsCard/ProductDetailsCard.tsx
  src/components/common/ProductDetailsCard/index.tsx
  src/test/ProductDetails/ProductDetailsCard.test.tsx
Labels: changes requested

#384 Feat/224 team card component
  src/components/common/TeamCard/teamcard.tsx
  src/test/teamcard.test.tsx
Labels: changes requested

#498 feat: The Password Strength Validator component is implemented accord…
  src/components/common/PasswordCheck/index.test.tsx
  src/components/common/PasswordCheck/index.tsx
Labels: changes requested

#468 Feat/165 email templat layout header and footer
  public/images/tiktok.svg
  src/app/(admin)/emailtemplates/footer/footer.test.tsx
  src/app/(admin)/emailtemplates/footer/index.tsx
  src/app/(admin)/emailtemplates/header/header.test.tsx
  src/app/(admin)/emailtemplates/header/index.tsx
  src/app/(home)/page.tsx
Labels: changes requested

#475 feat/105 create subscription renewal failed email template
  .github/workflows/dev-cicd.yml
  .github/workflows/staging-cicd.yml
  .vscode/extensions.json
  .vscode/settings.json
  STYLE_GUIDE.MD
  components.json
  docker/staging/docker-compose.yml
  pnpm-lock.yaml
  public/images/Star1.svg
  public/images/subscription-payment-error.svg
  src/components/common/Breadcrumb/README.md
  src/components/common/Button/README.md
  src/email/templates/subscriptionRenewalFailed/with-image.tsx
  src/email/templates/subscriptionRenewalFailed/zodSchema.tsx
  src/test/subscriptionRenewalFailed.test.tsx
  tsconfig.json
Labels: changes requested

#411 Feat/hng 183 create badge component
  src/app/guides/page.tsx
  src/components/common/Badge/Badge.tsx
  src/test/Badge.test.tsx
Labels: changes requested

#494 Feat/hng 19 authentication page success page for magic link
  .gitignore
  package-lock.json
  src/components/ui/button.tsx
  src/pages/login/EmailSent.tsx
  src/pages/login/__tests__/EmailSent.test.tsx
Labels: changes requested

#508 Feat/10 profile settings page
  .gitignore
  pnpm-lock.yaml
  src/app/(admin)/admin/page.test.tsx
  src/app/contact/constants.js
  src/app/contact/page.tsx
  src/app/globals.css
  src/app/settings/layout.tsx
  src/app/settings/profile/index.tsx
  src/app/settings/stateContext.tsx
  src/components/ui/form.tsx
  src/components/ui/select.tsx
Labels: completed

#484 Feat/hng 4 create signup page
  public/signup/icons/bi_facebook.svg
  public/signup/icons/flat-color-icons_google.svg
  src/app/signup/page.test.tsx
  src/app/signup/page.tsx
Labels: changes requested

#536 Feat/hng 102 subscription renewal reminder template
  src/email/templates/subscriptionRenewalReminder/with-image.tsx
  src/test/SubscriptionEmailTemplate.test.tsx
Labels: changes requested

#385 Feat/38 implement the password settings page
  src/app/FaqAccordion/index.tsx
  src/app/guides/page.tsx
  src/app/guides/preview/PlaceholderPage.tsx
  src/app/guides/template-editor/PlaceholderPage.tsx
  src/app/settings/layout.tsx
  src/app/settings/page.tsx
  src/components/common/Button/button.tsx
  src/components/common/Button/index.tsx
  src/components/common/CareerCard/CareerCard.tsx
  src/components/common/CareerCard/index.tsx
  src/components/common/Comment/ButtonWrapper.tsx
  src/components/common/FormPage/CheckmarkIcon.tsx
  src/components/common/FormPage/PasswordChecks.tsx
  src/components/common/FormPage/UpdatePassword.tsx
  src/components/ui/alert-dialog.tsx
Labels: changes requested

#428 Feat/hng 182 manage members invite alert
  src/app/settings/manage-members/page.tsx
  src/components/common/customToast/toast.tsx
  src/components/ui/toast.tsx
  src/test/settings/manage-members/toast.test.tsx
Labels: changes requested

#456 Feat/84 implement subscription and plan overview page
  public/icon.png
  public/tick-icon.svg
  src/app/api/userdata.ts
  src/app/layout.tsx
  src/app/subscription-and-plan/page.tsx
  src/app/subscription-and-plan/subscriptionandplan.test.tsx
Labels: changes requested

#458 Feat/hng 118 email template paginated table list
  public/images/emailConfirmation.png
  src/app/guides/page.tsx
  src/components/common/PaginatedTemplateList/PaginatedTemplateList.tsx
  src/components/common/Pagination/Pagination.test.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/common/TemplateListItem/TemplateListItem.test.tsx
  src/components/common/TemplateListItem/TemplateListItem.tsx
  src/constants/templateList.ts
Labels: changes requested

#559 Feat/hng 41 member page and export funtionality
  src/app/settings/members/page.tsx
  src/components/exportToCSV/ExportToCsv.tsx
Labels: changes requested

#525 Feat/hng 4 create signup page
  public/signup/icons/bi_facebook.svg
  public/signup/icons/flat-color-icons_google.svg
  src/app/signup/page.test.tsx
  src/app/signup/page.tsx
Labels: changes requested

#438 feat: implement login with magic link
  public/images/shield.svg
  src/app/auth/Login.tsx
  src/app/guides/page.tsx
  src/test/MagicLogin.test.tsx
Labels: changes requested

#541 78 feat super admin dashboard page
  public/icons/arrowUp.svg
  public/icons/box.svg
  public/icons/dollarSign.svg
  public/icons/user.svg
  src/app/(admin)/admin/dashboard/client.tsx
  src/app/(admin)/admin/dashboard/page.tsx
  src/app/guides/page.tsx
  src/components/adminDashboard/CardComponent.tsx
  src/components/adminDashboard/Chart.tsx
  src/components/adminDashboard/TopProductsComponent.tsx
  src/components/adminDashboard/cardData.ts
  src/components/adminDashboard/chartData.ts
  src/components/adminDashboard/productData.ts
  src/test/adminDashboard/CardComponent.test.tsx
  src/test/adminDashboard/TopProductsComponent.test.tsx
Labels: changes requested

#338 Feat/hng 213 component media file upload
  src/components/MediaUpload/index.tsx
  src/test/MediaUpload.test.tsx
Labels: changes requested

#638 Refactor/restructure-email-templates
  src/app/(admin)/admin/_components/navbar/AdminNavbar.test.tsx
  src/app/(admin)/admin/_components/navbar/AdminNavbar.tsx
  src/app/(admin)/admin/_components/unread-notification-card/UnreadNotificationCard.tsx
  src/app/(admin)/admin/page.tsx
  src/app/(admin)/layout.tsx
  src/components/layouts/footer/footer.test.tsx
  src/components/ui/avatar.tsx
  src/components/ui/card.tsx
  src/components/ui/popover.tsx
  src/components/ui/switch.tsx
  src/email/templates/_components/layout/layout.tsx
  src/email/templates/_components/template-footer/EmailFooter.tsx
  src/email/templates/_components/template-header/EmailHeader.tsx
  src/email/templates/dummy/no-image.tsx
  src/email/templates/password-reset/no-image.tsx
Labels: enhancement
